services:
  - type: web
    name: linkedin-poster
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true 
    
cronJobs:
  - name: daily-linkedin-post
    schedule: "0 9 * * *"  # This runs every day at 9 AM UTC
    command: "python main.py"
