services:
  - type: web
    name: linkedin-poster
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && pip install 'numpy>2' --no-deps"
    startCommand: "python main.py"
    autoDeploy: true 
    
cronJobs:
  - name: daily-linkedin-post
    schedule: "22 17 * * *"  # This runs every day at 5:12 PM UTC
    command: "python main.py"
